export default {
  "login": "erdldncr",
  "id": 72579283,
  "node_id": "MDQ6VXNlcjcyNTc5Mjgz",
  "avatar_url": "https://avatars.githubusercontent.com/u/72579283?v=4",
  "gravatar_id": "",
  "url": "https://api.github.com/users/erdldncr",
  "html_url": "https://github.com/erdldncr",
  "followers_url": "https://api.github.com/users/erdldncr/followers",
  "following_url": "https://api.github.com/users/erdldncr/following{/other_user}",
  "gists_url": "https://api.github.com/users/erdldncr/gists{/gist_id}",
  "starred_url": "https://api.github.com/users/erdldncr/starred{/owner}{/repo}",
  "subscriptions_url": "https://api.github.com/users/erdldncr/subscriptions",
  "organizations_url": "https://api.github.com/users/erdldncr/orgs",
  "repos_url": "https://api.github.com/users/erdldncr/repos",
  "events_url": "https://api.github.com/users/erdldncr/events{/privacy}",
  "received_events_url": "https://api.github.com/users/erdldncr/received_events",
  "type": "User",
  "site_admin": false,
  "name": 'Erdal Dincer',
  "company": null,
  "blog": "",
  "location": 'England',
  "email": 'erdldncr@gmail.com',
  "hireable": null,
  "bio": 'FullStack Web Developer ',
  "twitter_username": 'erdldncr',
  "public_repos": 100,
  "public_gists": 0,
  "followers": 0,
  "following": 8,
  "created_at": "2020-10-08T20:45:58Z",
  "updated_at": "2021-05-01T11:38:31Z"
};